Put the panic handler behind a feature flag
probe-rs/flash-algorithm pull request #2
Opened 2023-02-11 04:17 UTC by tgross35

Shipping with a panic handler was messing my [docs with crates that had >1 binary](https://github.com/rust-lang/rust/issues/107918). Not sure why that issue exists and it's not this crate's fault, but I figured putting the handler behind a feature flag isn't a bad idea just in case somebody wants something specific.

I don't currently have hardware to test this with, so please verify this works as intended if you are able to.

2023-02-11 08:14 UTC, Tiwalun requested changes
Thanks, that's a good addition!

Just a small nit regarding the actual behaviour of the handler, other than that it's good to go.

2023-02-11 08:14 UTC, Tiwalun commented on src/lib.rs
> +//!   handler.
```suggestion
//! - `panic-handler` this is enabled by default and includes a simple panic
//!   handler which aborts on panic. Disable this feature flag if you would prefer to use a different
//!   handler.
```

2023-02-24 03:37 UTC, tgross35 commented
Whoops, sorry I missed that! I did the change, should be all set now

2023-02-24 12:04 UTC, Yatekii approved these changes

2023-02-24 12:04 UTC, merged